'use strict';
/**
 * architect.js — The Architect: Pattern & Exception Engine
 *
 * Responsibilities:
 *  1. Takes a neutralized spec from The Shield
 *  2. Generates a Mermaid dependency graph (spatial tree)
 *  3. Drafts edge-case unit tests targeting logic extremes
 *  4. Returns a FROZEN, immutable plan object for the Executioner
 *
 * The plan is the system's single source of truth — once locked, nothing changes it.
 */

const localBot2 = require('./local-bot');
const shield = require('./shield');

// ── Mermaid Generator (local, zero API cost) ──────────────────────────────────

class MermaidGenerator {
    /**
     * Generate a Mermaid flowchart from a structured spec.
     * This runs locally — no API call needed.
     */
    fromSpec(spec, title = 'Task Plan') {
        const lines = ['flowchart TD'];
        lines.push(`    A([🚀 Start: ${this._safe(title)}])`);

        // Parse spec lines into nodes
        const specLines = spec.split('\n').filter(l => l.trim());
        let prevNode = 'A';
        let nodeIdx = 1;

        for (const line of specLines) {
            const nodeId = `N${nodeIdx}`;
            const label = this._safe(line.trim().slice(0, 60));
            const shape = line.startsWith('ACTION') ? `[${label}]`
                : line.startsWith('CONSTRAINT') ? `{${label}}`
                : line.startsWith('SUCCESS') ? `(${label})`
                : `[${label}]`;
            lines.push(`    ${nodeId}${shape}`);
            lines.push(`    ${prevNode} --> ${nodeId}`);
            prevNode = nodeId;
            nodeIdx++;
        }

        lines.push(`    ${prevNode} --> Z([✅ Done])`);
        return lines.join('\n');
    }

    /**
     * Generate a Mermaid graph from an AI-generated plan text.
     * Parses numbered/bulleted steps into a sequential flowchart.
     */
    fromPlanText(planText, title = 'Implementation Plan') {
        const lines = ['flowchart TD'];
        lines.push(`    START([🎯 ${this._safe(title.slice(0, 50))}])`);

        // Extract steps from plan (numbered list or bullet points)
        const stepPattern = /^[\s]*(?:\d+[\.\)]\s*|[-*•]\s*|\[.\]\s*)(.+)/gm;
        const steps = [];
        let m;
        while ((m = stepPattern.exec(planText)) !== null) {
            steps.push(m[1].trim().slice(0, 70));
        }

        if (steps.length === 0) {
            // Fallback: use first 5 sentences
            const sentences = planText.split(/[.!?]+/).filter(s => s.trim().length > 10).slice(0, 5);
            steps.push(...sentences.map(s => s.trim().slice(0, 70)));
        }

        let prev = 'START';
        steps.forEach((step, i) => {
            const id = `S${i + 1}`;
            const isDecision = step.toLowerCase().includes('if ') || step.toLowerCase().includes('check');
            const shape = isDecision ? `{${this._safe(step)}}` : `[${this._safe(step)}]`;
            lines.push(`    ${id}${shape}`);
            lines.push(`    ${prev} --> ${id}`);
            prev = id;
        });

        lines.push(`    ${prev} --> DONE([✅ Complete])`);
        return lines.join('\n');
    }

    _safe(str) {
        return String(str).replace(/['"<>{}[\]]/g, ' ').replace(/\s+/g, ' ').trim();
    }
}

// ── Edge Case Test Generator (local, zero API cost) ───────────────────────────

class EdgeCaseGenerator {
    /**
     * Given a spec, generate JavaScript unit test stubs targeting extremes.
     */
    generate(spec, planText = '') {
        const action = this._extractAction(spec);
        const target = this._extractTarget(spec);

        const tests = [];
        const testTarget = target.replace(/[^a-zA-Z0-9]/g, '_').slice(0, 30) || 'implementation';

        tests.push(`// Auto-generated edge case tests for: ${target}`);
        tests.push(`// Generated by The Architect at ${new Date().toISOString()}\n`);
        tests.push(`describe('${testTarget}', () => {`);

        // Null/undefined inputs
        tests.push(`  it('handles null input gracefully', () => {`);
        tests.push(`    expect(() => ${testTarget}(null)).not.toThrow();`);
        tests.push(`  });\n`);

        // Empty string inputs
        tests.push(`  it('handles empty string input', () => {`);
        tests.push(`    expect(() => ${testTarget}('')).not.toThrow();`);
        tests.push(`  });\n`);

        // Overflow / boundary
        tests.push(`  it('handles maximum boundary value', () => {`);
        tests.push(`    expect(() => ${testTarget}(Number.MAX_SAFE_INTEGER)).not.toThrow();`);
        tests.push(`  });\n`);

        // Concurrent execution
        tests.push(`  it('is safe under concurrent calls', async () => {`);
        tests.push(`    const calls = Array.from({ length: 10 }, () => Promise.resolve(${testTarget}('concurrent_test')));`);
        tests.push(`    await expect(Promise.all(calls)).resolves.toBeDefined();`);
        tests.push(`  });\n`);

        // Action-specific tests
        if (action === 'fix' || action === 'optimize') {
            tests.push(`  it('produces same output as baseline on valid input', () => {`);
            tests.push(`    const baseline = 'expected_result';`);
            tests.push(`    expect(${testTarget}('valid_input')).toEqual(baseline);`);
            tests.push(`  });\n`);
        }

        if (action === 'analyze' || action === 'build') {
            tests.push(`  it('returns structured output (not undefined/null)', () => {`);
            tests.push(`    const result = ${testTarget}('test_input');`);
            tests.push(`    expect(result).toBeDefined();`);
            tests.push(`    expect(result).not.toBeNull();`);
            tests.push(`  });\n`);
        }

        // Error propagation
        tests.push(`  it('throws meaningful error on invalid input type', () => {`);
        tests.push(`    expect(() => ${testTarget}({ invalid: true })).toThrow();`);
        tests.push(`  });`);
        tests.push(`});\n`);

        return tests.join('\n');
    }

    _extractAction(spec) {
        const m = spec.match(/^ACTION:\s*(\w+)/m);
        return m ? m[1].toLowerCase() : 'build';
    }

    _extractTarget(spec) {
        const m = spec.match(/^TARGET:\s*(.+)/m);
        return m ? m[1].trim().slice(0, 60) : 'task';
    }
}

// ── The Architect ─────────────────────────────────────────────────────────────

class Architect {
    constructor() {
        this.mermaid = new MermaidGenerator();
        this.edgeCases = new EdgeCaseGenerator();
    }

    /**
     * Main entry: plan → Mermaid graph → edge tests → frozen plan object.
     * @param {string} rawPrompt - The user's raw prompt
     * @param {object} options - { emitMermaid(chunk), targetFiles }
     * @returns {object} Frozen plan object for the Executioner
     */
    async plan(rawPrompt, options = {}) {
        const { emitMermaid, targetFiles = [] } = options;
        const planId = `plan_${Date.now()}`;

        // ── Stage 1: Neutralize with Shield ──────────────────────────────────
        const shieldResult = shield.neutralize(rawPrompt);
        console.log(`[ARCHITECT] Shield confidence: ${shieldResult.confidence}. Proceeding to plan.`);

        // ── Stage 2: Generate Mermaid from spec locally (free) ───────────────
        const specMermaid = this.mermaid.fromSpec(shieldResult.spec, 'Analysis');
        if (emitMermaid) emitMermaid({ type: 'spec_graph', mermaid: specMermaid });

        // ── Stage 3: Ask AI for implementation plan ───────────────────────────
        const systemPrompt = [
            'You are The Architect — a precise, logical AI that generates implementation plans.',
            'Your output MUST be a numbered list of concrete, actionable steps.',
            'Each step should be specific and testable. No vague instructions.',
            'Target files (if any): ' + (targetFiles.length > 0 ? targetFiles.join(', ') : 'entire codebase')
        ].join('\n');

        let planText = '';
        try {
            planText = await localBot2.call(shieldResult.spec + '\n\nNEUTRALIZED:\n' + shieldResult.neutralized, 'worker', systemPrompt, 800);
        } catch (e) {
            console.log(`[ARCHITECT] Worker failed (${e.message}). Escalating to reviewer.`);
            try {
                planText = await localBot2.call(shieldResult.neutralized, 'reviewer', systemPrompt, 800);
            } catch (e2) {
                // Fallback: generate plan from spec locally
                planText = this._generateLocalPlan(shieldResult);
            }
        }

        // ── Stage 4: Generate plan Mermaid ────────────────────────────────────
        const planMermaid = this.mermaid.fromPlanText(planText, rawPrompt.slice(0, 50));
        if (emitMermaid) emitMermaid({ type: 'plan_graph', mermaid: planMermaid });

        // ── Stage 5: Generate edge-case tests ─────────────────────────────────
        const edgeCaseTests = this.edgeCases.generate(shieldResult.spec, planText);

        // ── Stage 6: Lock the plan ────────────────────────────────────────────
        const plan = Object.freeze({
            id: planId,
            createdAt: new Date().toISOString(),
            originalPrompt: rawPrompt,
            shieldResult: Object.freeze({ ...shieldResult }),
            planText,
            specMermaid,
            planMermaid,
            edgeCaseTests,
            targetFiles: Object.freeze([...targetFiles]),
            steps: this._extractSteps(planText),
            locked: true
        });

        console.log(`[ARCHITECT] Plan ${planId} locked with ${plan.steps.length} steps.`);
        return plan;
    }

    /** Lock a plan object — returns a frozen copy. */
    lock(plan) {
        return Object.freeze({ ...plan, locked: true });
    }

    _generateLocalPlan(shieldResult) {
        return [
            `1. Analyze: ${shieldResult.target || 'the target system'}`,
            `2. Implement: ${shieldResult.action || 'the required changes'}`,
            `3. Test: Validate all constraints: ${(shieldResult.constraints || []).join(', ') || 'none specified'}`,
            `4. Verify: Confirm success criteria: ${(shieldResult.successCriteria || []).join(', ') || 'none specified'}`,
            `5. Document: Summarize output and inject into notebook exports`
        ].join('\n');
    }

    _extractSteps(planText) {
        const stepPattern = /^[\s]*(?:\d+[\.\)]\s*|[-*•]\s*)(.+)/gm;
        const steps = [];
        let m;
        while ((m = stepPattern.exec(planText)) !== null) {
            steps.push(m[1].trim());
        }
        return steps.length > 0 ? steps : [planText.slice(0, 200)];
    }
}

module.exports = new Architect();
module.exports.Architect = Architect;
module.exports.MermaidGenerator = MermaidGenerator;
module.exports.EdgeCaseGenerator = EdgeCaseGenerator;
